namespace Wasit.Core.Enums
{
    public enum NotifyTypes
    {
        DeactivateUser = -1,
        RemoveUser = -2,
        NotifyFromDashBord = 0,
        AddNewEstate = 1,
        EstateIsApproved = 2,
        RequestAccepted = 3,
        RequestRejected = 4,
        NewPricingRequest = 5,
        EstateIsSoldOrRentedConfirmation = 6,
        NewPriceToEstate = 7,
        NewPurchaseRequest = 8,
        NewEvaluationRequest = 9,
        NewReservationRequest = 10,
        CancelPurchaseRequest = 11,
        PayDposit = 12,
        ConfirmEstateIsReceived = 13,
        NewRefundRequest = 14,
        NewRatingForDelegate = 15,
        FinishedReservationRequestConsumer = 16,
        FinishedReservationRequestPublisher = 17,
        EvaluationRequestIsAcceptedConsumer = 18,
        EvaluationRequestIsAcceptedPublisher = 19,
        NewRentRequest = 20,
        CancelRentRequest = 21,
        PayRent = 22,
        NewRatingForPublisher = 23,
        NewRatingForConsumer = 24,
        NewReport = 25,
        NewDailyRentRequest = 26,
        CancelDailyRentRequest = 27,
        DailyOrEntertainmentRentStartedConsumer = 28,
        DailyOrEntertainmentRentStartedPublisher = 29,
        DailyOrEntertainmentRentFinishedConsumer = 30,
        DailyOrEntertainmentRentFinishedPublisher = 31,
        NewEntertainmentRentRequest = 32,
        CancelEntertainmentRentRequest = 33,
        NewRentalManagementRequest = 34,
        CancelRentalManagementRequest = 35,
        TerminateRentalManagementRequest = 36,
        NewMaintainanceManagementRequest = 37,
        NewMaintainanceRatingForDelegate = 38,
        ApartmentRentPaid = 39,
        EvaluationRequestIsDeletedConsumer = 40,
        FinishedLongRentPeriodConsumer = 41,
        FinishedLongRentPeriodPublisher = 42,
        RemindPublisherToSetBookingPeriod = 43,
        RejectedRentalManagementRequest = 44,
        EstateIsRejected = 45
    }
}
